PACKAGE_NAME="zcan_usb"
PACKAGE_VERSION="0.5.1"
BUILT_MODULE_NAME[0]="zcan_usb"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
CLEAN="make clean"
